trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      ls -a $(Build.ArtifactStagingDirectory)
      mv '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).jar' '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'