trigger:
- master

jobs:
- job: build
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      echo Starting the build
      env
      java -version
      ./mvnw clean package 
    displayName: 'Build with Maven'
