trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'    
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: '-Dmaven.test.skip package'

- task: CopyFiles@2
  inputs:
    Contents: '/home/vsts/work/1/s/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'    
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      cd  '$(Build.ArtifactStagingDirectory)/target'
      ls  '$(Build.ArtifactStagingDirectory)/target'
      mv 'BulkSmsApp-0.0.1-SNAPSHOT.jar' 'BulkSmsApp-0.0.1-SNAPSHOT.zip'
      ls  '$(Build.ArtifactStagingDirectory)/target'
     
- task: S3Upload@1
  inputs:
    awsCredentials: 'azure_user_aws'
    regionName: 'us-east-1'
    bucketName: 'azureb1'
    globExpressions: '*.zip'
    createBucket: true